### ISSUE TITLE
x-for elements disappearing after Livewire rerender

### ISSUE THREAD

**Issue by zepfietje** [SimoTod/alpine-turbolinks-adapter#16]
`x-for` elements are no longer rendered after being hidden by a Livewire action.
If you go to https://picci.app/new and toggle the Picci type to "Text" and back to "Date", the date picker `x-for` items are no longer rendered.

I'm not sure what could be the cause of this bug, but I've confirmed it only happens when using the `alpine-turbolinks-adapter`.

**Comment by SimoTod** [comment]
Hi @zepfietje , it's a bit hard to debug on a remote app where all Javascript is already bundled. 
I would expect the adapter to kick in only when you load a new page.
Do you have a simple snippet I can use to replicate? Thanks

**Comment by zepfietje** [comment]
@SimoTod I've put together a minimal example which shows the bug.  
If you enable and disable the `alpine-turbolinks-adapter`, you'll see the bug only occurs when the adapter is installed.

`app/Http/Livewire`
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Example extends Component
{
    public $show = true;

    public function render()
    {
        return view('livewire.example');
    }
}
```

`resources/views/livewire/example.blade.php`
```blade.php
<div>
    <button wire:click="$toggle('show')">Toggle</button>
    @if ($show)
        <div x-data>
            <h1>Example</h1>
            <div>
                <template x-for="index in [1, 2, 3]">
                    <span x-text="index"></span>
                </template>
            </div>
        </div>
    @endif
</div>
```

**Comment by SimoTod** [comment]
Thanks @zepfietje 
I think I found the problem. Can you test https://cdn.jsdelivr.net/gh/simotod/alpine-turbolinks-adapter@bug/livewire-show/dist/alpine-turbolinks-adapter.min.js and let me know if it fixes that bug?

**Comment by zepfietje** [comment]
I've tested the fix on both [Picci](https://picci.app) and the example snippets and can confirm it fixes the bug.

Thanks @SimoTod!

**Comment by SimoTod** [comment]
Thanks again for being such a good beta tester. :)
I've tagged a new patch release. As usual, it will take a bit to go through the CDN but you should be able to see the updated version tomorrow-ish.

**Comment by zepfietje** [comment]
@SimoTod, strangely the bug is still present after updating to the latest version from npm (`0.1.3`).  
The CDN link from the bugfix branch does really fix the issue though. So possibly something went wrong just before releasing the latest version?

**Comment by SimoTod** [comment]
The cdn link won't work until tomorrow. I tagged a version without merging the fix, then I realised it and I retagged the right veraion (my tagging process automatically updates to npm) but since i visited the link, cdn had already cached the wrong version. If you build the assets yourself or if you use the cdn link from github it should work otherwise you can wait 24h

**Comment by zepfietje** [comment]
Since I'm using npm and not the CDN link, could you tag a new version so the bugfix also appears on npm?

**Comment by SimoTod** [comment]
Ah, that's weird. I did unpublish the wrong version before retagging 0.1.3 so it should serve the right file from npm. I'm not at my laptop now, I'll have a look as soon as I can and if needed I'll tag a new version

**Comment by SimoTod** [comment]
Right, apparently what I was trying to do (unpublish and republish) is not possible anymore(https://blog.npmjs.org/post/77758351673/no-more-npm-publish-f)
I've tagged a new version

**Comment by zepfietje** [comment]
Thanks, got it all working now!
