### ISSUE TITLE
v0.2.0 - x-for loop items disappear

### ISSUE THREAD

**Issue by zepfietje** [SimoTod/alpine-turbolinks-adapter#19]
After upgrading to v0.2.0, I noticed a bug similar to #16.
`x-for` children are no longer rendered after a Livewire rerender.
Similar steps to the other issue description (note: I haven't installed v0.2.0 in production):
> If you go to https://picci.app/new and toggle the Picci type to "Text" and back to "Date", the date picker x-for items are no longer rendered.

I've been able to reproduce the issue using the example I posted earlier for the other issue.
https://github.com/SimoTod/alpine-turbolinks-adapter/issues/16#issuecomment-683297409

As far as I've been able to debug:
- does not occur pre v0.2.0;
- occurs when directly loading the page;
- does not occur when navigating to the page from another page.

**Comment by SimoTod** [comment]
I don't assume you can defer livewire right? In that case you need to make the library not deferred.
I'll see if there is a better way but that would work for now.

**Comment by zepfietje** [comment]
Making it not deferred isn't a real solution for me.
I'd like to compile everything into a single `app.js` file and have that one deferred.

**Comment by SimoTod** [comment]
Fixed in 0.2.1
