### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by bep** [SimoTod/alpine-turbolinks-adapter#22]
Note that I would not bother opening this issue if I thought this would be "hard to do", but since Alpine supports (to some extent) IE 11 and I suspect this is about adjusting your Babel config (to turn classes into function), maybe that could be done?

**Comment by SimoTod** [comment]
Probably. I don't think we do anything too weird so we probably the final output will be similar and we don't need separate builds like in alpine. I'll have a play over the weekend. Thanks for pointing this out.

**Comment by SimoTod** [comment]
does https://cdn.jsdelivr.net/gh/simotod/alpine-turbolinks-adapter@73fab37d2d79b39e9c475af67c81fe5e86610692/dist/alpine-turbolinks-adapter.min.js work okay for you?

**Comment by bep** [comment]
That looks great to me, much appreciated.

**Comment by SimoTod** [comment]
Thanks for confirming. I've just tagged v0.3.0 containing the patch to support legacy browsers.
